include("/opt/homebrew/share/cmake/Modules/GoogleTestAddTests.cmake")
gtest_discover_tests_impl(
  TEST_TARGET [==[lattice_tests]==]
  TEST_EXECUTABLE [==[/Users/amankarki/Downloads/projects/lattice/build-cov/core/tests/lattice_tests]==]
  TEST_EXECUTOR [==[]==]
  TEST_WORKING_DIR [==[/Users/amankarki/Downloads/projects/lattice/build-cov/core/tests]==]
  TEST_EXTRA_ARGS [==[]==]
  TEST_PROPERTIES [==[]==]
  TEST_PREFIX [==[]==]
  TEST_SUFFIX [==[]==]
  TEST_FILTER [==[]==]
  NO_PRETTY_TYPES [==[FALSE]==]
  NO_PRETTY_VALUES [==[FALSE]==]
  TEST_LIST [==[lattice_tests_TESTS]==]
  CTEST_FILE [==[/Users/amankarki/Downloads/projects/lattice/build-cov/core/tests/lattice_tests_e3b0c442_tests.cmake]==]
  TEST_DISCOVERY_TIMEOUT [==[5]==]
  TEST_DISCOVERY_EXTRA_ARGS [==[]==]
  TEST_XML_OUTPUT_DIR [==[]==]
  TEST_JSON_OUTPUT_DIR [==[/Users/amankarki/Downloads/projects/lattice/build-cov/core/tests]==]
)
